export const GET_FREELANCERS_SUCCESS = "GET_FREELANCERS_SUCCESS"
export const GET_VALIDATED_FREELANCERS_SUCCESS = "GET_VALIDATED_FREELANCERS_SUCCESS"
export const GET_UNVALIDATED_FREELANCERS_SUCCESS = "GET_UNVALIDATED_FREELANCERS_SUCCESS"
export const GET_FREELANCER_BY_ID_SUCCESS = "GET_FREELANCER_BY_ID_SUCCESS"


export const GET_ALL_TASKS_SUCCESS = "GET_ALL_TASKS_SUCCESS" 
export const GET_TO_DO_TASKS_SUCCESS = "GET_TO_DO_TASKS_SUCCESS" 
export const GET_IN_PROGRESS_TASKS_SUCCESS = "GET_IN_PROGRESS_TASKS_SUCCESS" 
export const GET_DONE_TASKS_SUCCESS = "GET_DONE_TASKS_SUCCESS" 

export const UPDATE_FREELANCER_SUCCESS = "UPDATE_FREELANCER_SUCCESS"
export const DELETE_FREELANCER_SUCCESS = "DELETE_FREELANCER_SUCCESS"